import "../css/shared/base.scss";
import "../css/shared/article-search.scss";
import "../css/shared/articles.scss";
import "../css/shared/breadcrumbs.scss";
import "../css/shared/footer.scss";
import "../css/shared/leaflets.scss";
import "../css/shared/navbar.scss";
import "../css/shared/pagination.scss";
import "../css/shared/pills.scss";
import "../css/shared/products.scss";
import "../css/shared/search.scss";
import "../css/shared/section.scss";
import "../css/shared/socials.scss";

import "./navbar/navbar.js";
import "./search/search.js";
import "./brands/brands.js";
import "./leaflets/leaflets.js";
import "./products/products.js";
